### PR TITLE
Fix step collisions

### LINKED ISSUE #41: Cucumber_Factory 2.2.0 will break a lot of tests
Hello,

I can't use a lot of steps since CF 2.2.0 anymore. Especially the time steps will break:
```
uninitialized constant TimeIs (NameError)
features/some_model/some_feature.feature:4:in `Given the time is "2019-04-11 11:00"'
```

The regular expressions `RECORD_UPDATE_PATTERN` and `UPDATE_ATTR_PATTERN` have to be more strict.

### PR DESCRIPTION
**Pull request by niklas-hasselmeyer**
- The priority of all cucumber_factory steps has been reduced to -2 / -1 with text attributes (from 0 / 1 with text attributes)
- The update step will get fewer "false matches" (model names cannot include quotes now, and at least one of `has the`, `belongs to the`, `is` and `has these attributes` has to appear)
Closes #41

### CODE REVIEW

File: lib/cucumber_factory/factory.rb [hunk 1]
```diff
@@ -4,12 +4,12 @@ class Error < StandardError; end
 
     ATTRIBUTES_PATTERN = '( with the .+?)?( (?:which|who|that) is .+?)?' # ... with the year 1979 which is science fiction
     TEXT_ATTRIBUTES_PATTERN = ' (?:with|and) these attributes:'
-    UPDATE_ATTR_PATTERN = '(?: (?:has|belongs to)( the .+?))?(?:(?: and| but|,)*( is .+?))?' # ... belongs to the collection "Fantasy" and is trending
+    UPDATE_ATTR_PATTERN = '(?: (?:has|belongs to)( the .+?)|(?: and| but|,)*( is .+?))' # ... belongs to the collection "Fantasy" | and is trending
```
Comment (makmic) [inline lib/cucumber_factory/factory.rb:7]: I hope the pipe `|` is not really part of the example :)
```suggestion
    UPDATE_ATTR_PATTERN = '(?: (?:has|belongs to)( the .+?)|(?: and| but|,)*( is .+?))' # ... belongs to the collection "Fantasy" and is trending
```

File: lib/cucumber_factory/factory.rb [hunk 2]
```diff
@@ -4,12 +4,12 @@ class Error < StandardError; end
...
     TEXT_UPDATE_ATTR_PATTERN = '(?: and|,)* has these attributes:'
 
     RECORD_PATTERN = 'there is an? (.+?)( \(.+?\))?' # Given there is a movie (comedy)
     NAMED_RECORD_PATTERN = '(?:"([^\"]*)"|\'([^\']*)\') is an? (.+?)( \(.+?\))?' # Given "LotR" is a movie
-    RECORD_UPDATE_PATTERN = 'the (.+?) (above|".+?"|\'.+?\')' # Given the movie "LotR" ...
+    RECORD_UPDATE_PATTERN = 'the ([a-zA-Z _-]+?) (above|".+?"|\'.+?\')' # Given the movie "LotR" ...
```
Comment (makmic) [inline lib/cucumber_factory/factory.rb:12]: It looks fine to me, but please do a double check on numbers.
If it's possible to have factories like `factory :my_user_2`, then it would now be excluded from this regex. If so, include `[0-9]`.

Or maybe we should go the other way and just exclude some characters: `[^'"<>:]` or similar.
This would still allow the user to name his models exotically, like with unicode chars :unicorn:

**Review by makmic — APPROVED** [review]
Well done @niklas-hasselmeyer !
I tested it in the project which was used when reporting the issue.
